#---------------------- SON LAS RUTAS Y CONSULTAS DE PAGOS

###
GET http://localhost:3001/concesionaria/TodosPagos HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/concesionaria/buscarpago/654332139b46101291ea15b3 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3001/concesionaria/registropago HTTP/1.1
Content-Type: application/json

{
    "cliente":"65420d9853bb45a7472f0695",
    "noVendedor":1,
    "monto":80000,
    "estatus":"Activo"
}

###
PUT http://localhost:3001/concesionaria/actualizarpago/654332139b46101291ea15b3 HTTP/1.1
Content-Type: application/json

{
    "cliente":"65420d9853bb45a7472f0695",
    "noVendedor":1,
    "monto":90000,
    "estatus":"Activo"
}

###
DELETE http://localhost:3001/concesionaria/eliminarpago/654332139b46101291ea15b3 HTTP/1.1
Content-Type: application/json