#---------------------- SON LAS RUTAS Y CONSULTAS DE VENTA

###
GET http://localhost:3001/concesionaria/Todasventa HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/concesionaria/buscarventa/ HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3001/concesionaria/registroventa HTTP/1.1
Content-Type: application/json

{
    "vehiculo":"65421d020c0d40e4b201ec6e",
    "noVendedor":3,
    "pago":,
    "cliente":,
}

###
PUT http://localhost:3001/concesionaria/actualizarventa/ HTTP/1.1
Content-Type: application/json

{
    "vehiculo":,
    "noVendedor":,
    "pago":,
    "cliente":,
}

###
DELETE http://localhost:3001/concesionaria/eliminarventa/ HTTP/1.1
Content-Type: application/json